### ISSUE TITLE
Blank state / Not found component for pages and views

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#108]
# Not found views for components

Any view that expects to display something, that has the potential to be blank should be considered a candidate for a "blank state", or some kind of "not found page".

Ideally, we could build a component to streamline this process, but many questions remain about what views need them, and how they look in them. The following are a few examples.

## Products not found (Grid)

**Design**
https://zpl.io/2y7KPDy

**Issue**
The product grid can sometimes be blank, either because of no products or because of filters.

**Q:** How does it look when there are no products found after filtering or just an empty list of products.
**Q:** What messages are displayed; what views remain to allow for correcting the situation

## Product not found (PDP)

**Design**
https://zpl.io/be46Wxm

**Issue**
A PDP page can be "missing" if a product is unpublished, or a link is shared with an error

**Q:** How does the page look when there is no product found.
**Q:** What messages are displayed; what views remain to allow for correcting the situation

## Page not found / generic not found 

The app itself needs a blank state to handle incorrect routes or even views like "no addresses, add new".

**Q:** What messages are displayed; what views remain to allow for correcting the situation

**Comment by aldeed** [comment]
@rymorgan Can you prioritize these empty state designs, and make sure empty state designs are part of your design checklist for all new designs going forward? I see empty cart and empty cart sidebar in Zeplin, but I don't see any of the ones @mikemurray mentioned.

As a general rule, I would like to require that we have empty and error states for all components when we initially create them.

**Comment by rymorgan** [comment]
@cassytaylor Hinted at the filtering functionality we want. Norstrom's is a good example of what we intend for how the filtering should work to avoid many blank states other than broken urls or other load errors. 

https://shop.nordstrom.com/c/designer-shoes?origin=topnav&cm_sp=Top%20Navigation-_-Designer-_-Shoes&offset=3&top=72

**Comment by aldeed** [comment]
Thanks! @spencern I am thinking we make two tickets for implementing these designs, one for grid with no products design and one to render the generic design for any route that doesn't exist, including PDP. Should I write those or are you?

@rymorgan @cassytaylor Can we also get at least one error state / message design? We can have a generic default behavior like "show error message in toast", and then override behaviors if we want for different pages and/or different error types. For example, we could have a different design for network connection errors (lost internet or our service is restarting) vs. application errors.

As a simple initial example to illustrate what we need:

1. I load a page showing the product grid
1. I lose internet
1. I apply a filter or change sort by
1. Grid switches to "loading" state
1. The request to update the grid view fails because I have no connection
1. What do I see?

**Comment by rymorgan** [comment]
@aldeed Are we able to return specific errors? Like, can we return something like -- "looks like you have a network error" or the like for your example? Or is it just generic?

**Comment by spencern** [comment]
@aldeed I didn't have a chance to get to these today, I could potentially get to them tomorrow.

**Comment by aldeed** [comment]
@rymorgan Yes, in general we can check the type of error. We won't necessarily know _why_ there is a network error, though. It could be down on their end, our end, or anywhere between. In theory we could do some extra checks to try to guess, but I'm not sure if that's necessary.

**Comment by rymorgan** [comment]
I think generic seems like the right call then. If a brand wants to inject some personality then they can costumize the errors.

**Comment by spencern** [comment]
@aldeed to create independent tickets for this issue and add them to the Humbolt sprint

**Comment by aldeed** [comment]
These have now all been implemented except empty grid. Created an issue for the grid: #160
