### ISSUE TITLE
Update checkout page to match new designs updates.

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction-next-starterkit#180]
The checkout page's top hat will be updated to something similar to the image below.
![checkout](https://user-images.githubusercontent.com/486340/42969032-c50f29d8-8b59-11e8-9702-00395dc8370e.png)

This issue is to use the updated top hat to match new design updates.

**Comment by willopez** [comment]
@rymorgan @cassytaylor looping you guys in.

**Comment by cassytaylor** [comment]
Hey, just went and updated all Checkout screens with the updated header on Zeplin. 

Screenshots:
![desktop](https://user-images.githubusercontent.com/36006187/42969914-00c3efd0-8b65-11e8-8b60-4a7c3579edb8.png)
Desktop

![mobile](https://user-images.githubusercontent.com/36006187/42969923-03f301b4-8b65-11e8-8178-6e0684fde5a0.png)
Mobile

**Comment by willopez** [comment]
Looking good! @rymorgan @cassytaylor I believe we should add the title "Checkout" in between the logo and cart, thoughts? 

Further, the font size for the "Free shipping + Free Returns" was updated from 12px => 14px, it looks like the grey bar needs a bit more top + bottom padding ...

**Comment by rymorgan** [comment]
Agree, on both counts, we're working on that. We're going to add "secure checkout" to the top bar. Just took a look across a spectrum of brands and that's a dominant trend and believe that type of language has shown to increase conversion.

**Comment by willopez** [comment]
@rymorgan @cassytaylor Great, I'll be on the look out for these updates to update the checkout page. Thanks both!

**Comment by cassytaylor** [comment]
@willopez the updated Checkout header has been added to the mocks on Zeplin. Just as a note, I didn't update the padding around the "Free Shipping + Free Returns" text because that would increase the height of the whole top bar - in turn meaning the design on each screen would need to be pushed down by X amount of pixels :grimacing: but I would suggest increasing the height of that bar to 35px from 30px.

![top bar copy](https://user-images.githubusercontent.com/36006187/43023865-875d4b3a-8c29-11e8-91ec-0e3de25277df.png)

**Comment by willopez** [comment]
Note about padding noted :) and the updated designs look good! thanks
