### ISSUE TITLE
Wire up actual checkout summary data

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#208]
@aldeed commented on [Tue Aug 07 2018](https://github.com/reactioncommerce/reaction-component-library/issues/195)

In the starter kit, on the checkout page.

This required building a checkout action for the summary with a simplified version of the mini-cart sans most of its controls.

**Comment by mikemurray** [comment]
@spencern Does this PR include the `side summary` and the `checkout action` that contains the summary?

![guest_checkout_-_accordion_-_enter_shipping_address_-_error_-_storefront_-_zeplin](https://user-images.githubusercontent.com/42217/43918563-3e4f4c14-9bc8-11e8-92cb-469b029f26db.png)

![guest_checkout_-_accordion_-_order_review_-_storefront_-_zeplin](https://user-images.githubusercontent.com/42217/43918555-39a3d982-9bc8-11e8-856e-28f22d34c6c7.png)

**Comment by mikemurray** [comment]
@spencern @reactioncommerce/design I also noticed, the [cart summary](https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5ada4347eda5814422ce39e2) and the [checkout summary](https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b197a1ca2d5663159876954) of visually different enough to be a new component / style configuration.

Not only that, "items:" and "subtotal:" are used in interchangeably. Items: <price> and items: <number of items> and "Item total" in place of subtotal.

**Comment by aldeed** [comment]
@mikemurray I say make this issue only about the one on the right side. I suspect the step 4 section might actually just be done directly inside the CheckoutActions that @nnnnat is working on. However, there would be one prerequisite issue (which you should create if necessary and do) to update `CartItems` and `CartItem` to take an `isReadOnly` prop and remove the quantity and remove buttons per the design if that is true.

@cassytaylor I think it's best if the terms "Items", "Item total", "Shipping", "Tax", and "Order total" are the same everywhere. Can you clarify what the desired terms are, and whether it's ok to make them the same everywhere (on checkout page and cart page and mini cart)? Can that summary block with the components be the same everywhere, too?

**Comment by aldeed** [comment]
Also should it be "Not calculated" or "-"?

**Comment by mikemurray** [comment]
This is what I have so far without any massive tweaks to the summary component.

![reaction___checkout](https://user-images.githubusercontent.com/42217/43923808-a1cf1f3a-9bd7-11e8-9f2c-357f8ad1cc37.png)

**Comment by cassytaylor** [comment]
Hey @aldeed and @mikemurray, in the Cart summary, let's make...
Subtotal -> Item total
Total -> Order total

And in Checkout -
Items -> Item total

In terms of making them the same component, I'd like to keep "Not calculated" for Shipping and Tax in Checkout, since it's more explicit than the dash. Dashes are more common for those values in Cart (when they haven't been calculated) across other websites, however. 

I think the only other stylistic difference between the Cart and Checkout summaries (aside form the grey background of the Cart summary, which I'd like to keep) is the divider line above "Order total" in the Checkout summary, and the font size/weight for the order total value. I'd be fine with making the Cart summary styling consistent with Checkout's. 

But from a product perspective, I'm not sure if these should be the same component, because oftentimes the messaging and styling of these summaries on other sites are different on purpose – mainly because they message that certain values will be calculated in checkout, etc. I'm curious if making these the same component would be problematic for people developing with Reaction in the future for that reason, if that makes sense :thinking_face:

**Comment by aldeed** [comment]
@cassytaylor Thanks, great points. We can use the same component in two places and that would not prevent someone from swapping in their own component in only one of those places. I think that would address your concern?

@mikemurray If the only differences would be bg color and dash vs. "Not calculated", those could be configured by props of a single summary component. But whatever you decide to do is fine, as long as the labels are the same everywhere.
