### ISSUE TITLE
Profile address book page

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-next-starterkit#245]
# Work
Create the profile address book page in starter kit

## Route
`/profile/address`

## Permissions
Show blank/404 if not logged in

## Components
- The left sidebar should be a separate component, which will be shared among all of the profile pages. For now, it only needs the account profile section on top and a single "Address book" menu item.
- The right side should have the AddressBook component from the component library.

## Design
https://zpl.io/2vYPqk7

### Loading
Show a loading page spinner while the data is loading.

**Comment by kieckhafer** [comment]
How do we want to handle other routes that will eventually be a part of the profile, such as orders?

At this point I've just created the `profile/address` route, but we should probably lay out a plan as to how to architect this before too much gets done on the profile.

**Comment by aldeed** [comment]
@kieckhafer Good question. We can add separate pages and routes for each as we create them, but maybe the sidebar can be in a single component that they all share?

**Comment by kieckhafer** [comment]
I'm having an issue with the way the name fields were built in the `AddressBook` component and the data that is saved to a users `account.addressBook`, and wanted to discuss how we should implement this.

The `AddressBook` component was built with both a `firstName` and `lastName` field ([as the designs showed](https://github.com/reactioncommerce/reaction-component-library/issues/256)). However, our `addressBook` object has only a `fullName` field on it. The `Account` SimpleSchema, as well as the GraphQL `Address` schema both provide only `fullName` as the data inside of an `addressBook` entry, not `firstName` or `lastName`.

`firstName` and `lastName` are available at the `account` level, but once you get down to `account.addressBook.[].` each address has its' own `fullName` field that is different from the name on the `account`.

It seems the solution should probably be to combine the two fields into a single `fullName` field inside the `AddressBook` component, that should solve the issue since this is how the data is stored anyway, but I wanted to make sure there wasn't any architectural reason ( @aldeed @spencern @nnnnat ) or design reason ( @cassytaylor @rymorgan ) or anything I'm missing before I made that update.

**Comment by kieckhafer** [comment]
@willopez @aldeed 

It doesn't seem like we are using the `<Profile />` component, or the `viewer.gql` query that's in the same folder as the component.

Looks like the component was a placeholder, and I'm not sure what the query is doing, as we have a basically identical and more robust query at a higher level in the app now.

Do you think I could delete this [extra query] (https://github.com/reactioncommerce/reaction-next-starterkit/blob/feat-kieckhafer-newAccountPage/src/components/Profile/viewer.gql#L8), and then use the `<Profile>` component for the address book profile i'm creating here?

**Comment by willopez** [comment]
@kieckhafer the `Profile` component can be safely removed, it was a proof of concept component.

**Comment by kieckhafer** [comment]
@willopez does that include the `viewer.gql` file inside that folder? I'm 99.9% sure that's not used anywhere, it seems like it was just for this Profile component.

**Comment by willopez** [comment]
Yes, the `Profile` folder in the components can be removed.
