### ISSUE TITLE
Country list orders countries by country code

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#322]
The list of countries that are loaded in the address creation form are not in alphabetical order.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/1203639/45853214-2ea54480-bd01-11e8-9edf-7397ddf630be.png">

**Comment by machikoyasuda** [comment]
The countries are from this `locales.json` file and the JSON objects themselves are just sorted by country code, which is not the same as sorting by country name: https://github.com/reactioncommerce/reaction-next-starterkit/blob/master/src/lib/utils/locales.json

**Comment by spencern** [comment]
@machikoyasuda how should we resolve this?

**Comment by nnnnat** [comment]
@spencern @machikoyasuda Looks like in RC we're loading that same data set, but mapping props to an array of simple "state" objects `{ label: "Germany", value: "DE" }`. The new `AddressForm` just excepts a raw `locales` object and maps that to the `Select`. 
[RC Code](https://github.com/reactioncommerce/reaction/blob/20ae0162559e159212e736a702bcbea221512cb6/imports/plugins/core/accounts/client/containers/addressBookContainer.js#L302)

I think one solution would be to have the `AddressForm` take same `locales` object as a prop but do the prop mapping in a similar fashion as the RC form does. 
I also think we should default a Country value as we do with the address form in RC.
[AddressForm Docs](https://stoic-hodgkin-c0179e.netlify.com/#!/AddressForm)

Another approach would be to update the `AddressForm` instead of taking a `locales` prop to take  `countries` and `regions` props to populate the selects and make the `locales` property mapping be the responsibility of the `withLocales` HOC in the starterkit. 

A quickish fix might also be to just reorder the `locales.json` file and commit it back to the starterkit/comp-lib.

Let me what y'all think and I can take this one.

**Comment by machikoyasuda** [comment]
I vote for for now: `A quickish fix might also be to just reorder the locales.json file and commit it back to the starterkit/comp-lib.`
