### ISSUE TITLE
Update status badge appearance and UX to match designs

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-next-starterkit#88]
Zeplin: http://zpl.io/V18RD3Q

## Work

Figure out all possible badges and prioritize. The applicable closest to top goes on the left of the product item, the next applicable goes on right side.
1. Sold Out or Backordered
2. Sale
3. Low Inventory
4. Bestseller

*Note: We don't have "Sale" and "Bestseller" implemented yet, but make a prioritization function that can handle them eventually.*

Example from Cassy:
> if an item is on sale, low inventory, and a bestseller, the Sale and Low Inventory badges would display (the thinking here is that “Low Inventory” conveys more of a sense of urgency for order conversion than the Bestseller badge).
> 
> If an item is on sale and a bestseller, Bestseller would be the secondary badge. 

If Sold Out or Backordered shows, then there is NEVER a secondary badge shown.

Update colors for primary (left) badge:
- Sold Out, Backordered - @cool-grey
- Low Inventory - @cool-grey

For simplicity, the secondary (right) text-only badge should just be @cool-grey.

**Comment by kieckhafer** [comment]
@cassytaylor can you please link the current version of the designs in this thread? The link in Eric's original post is no longer valid, probably moved during the zeplin re-org.

**Comment by cassytaylor** [comment]
@kieckhafer here's the link to the screen showing primary & secondary badges (updated in the main issue as well) - http://zpl.io/V18RD3Q

**Comment by cassytaylor** [comment]
@aldeed and @spencern, PDP mocks for badging are now available-

**Zeplin mocks:**
Web: https://zpl.io/bzMBLpz
App: [zpl://project?tags=badging&pid=5afc82f5e8d73e250ff9d855](zpl://project?tags=badging&pid=5afc82f5e8d73e250ff9d855)

There are three types of PDP badging/messaging, used in different placements: 
**Inventory badges** show up below option when variant and option have been selected.
**Sale/promotion badges** are the only badges that show up on the variant.
**Merchandising badges** show only on the large variant or option images.

**Sale:**
A Sale variant is depicted with the Sale badge (also used on the PDP) over the variant thumbnail image. This makes Sale variants easy to identify, especially coming from the product grid, where the 'Sale' badge would be shown if only one variant is on sale.
![screen shot 2018-06-01 at 3 21 39 pm](https://user-images.githubusercontent.com/36006187/40864119-b06f0acc-65af-11e8-994f-b235202d47dc.png)

**Low inventory, out of stock, backordered messaging:**
These product statuses are conveyed through a message below the Variant option ("size" in the mocks), since these statuses generally happen at that level; 
![screen shot 2018-06-01 at 3 21 52 pm](https://user-images.githubusercontent.com/36006187/40864160-f00b96aa-65af-11e8-9896-27f66d161127.png)
^ low inventory variant option

![screen shot 2018-06-01 at 3 21 57 pm](https://user-images.githubusercontent.com/36006187/40864165-f5ffa236-65af-11e8-808b-05f86e061c17.png)
^ this depicts a variant that is completely sold out; sold out options are shown as disabled.

![screen shot 2018-06-01 at 3 32 01 pm](https://user-images.githubusercontent.com/36006187/40864418-fbfca462-65b0-11e8-9bf6-8a758ced3b06.png)
^ backordered messaging. a user can still add this item to their cart & check out.

**Bestseller:**
This badge is shown over the main product image on the PDP. TBD if the "Bestseller" status is at the product, or variant level.
![screen shot 2018-06-01 at 3 26 06 pm](https://user-images.githubusercontent.com/36006187/40864211-278faa44-65b0-11e8-9f81-57eefa0ba275.png)

**Comment by aldeed** [comment]
Thanks @cassytaylor, makes sense.

@kieckhafer I will make separate issues for those new designs. Just do product grid designs in this issue.

**Comment by kieckhafer** [comment]
@aldeed @spencern It seems currently our `Badge` component is only used for Inventory badges. Are we going to expand it's usage in the future?

We do a lot of the inventory logic inside of the `Badge` component, should this be moved into a new `InventoryBadge` component which wraps the badge component?

**Comment by aldeed** [comment]
@kieckhafer We had a plan in the planning meeting, but seeing the new designs, I think this will be altered a bit now. Here's what I'm thinking:

(1) Remove existing `Badge` component

(2) Make a new `BadgeOverlay` component that renders its children in a wrapper div with the primary and secondary badges fixed to the top left and right corners of the wrapper div.

(3) Update `ProductItem` to wrap the `renderProductMedia` div in the new `BadgeOverlay`

(4) Update `ProductDetailOptionsList` to wrap each option image in the new `BadgeOverlay`, but pass it some prop that says "filter out all badges except Sale"

(5) Update `MediaGallery` to wrap the `renderFeaturedImage` in the new `BadgeOverlay`, but pass it some prop that says "filter out all badges except merchandising badges"

I know those "filter out" props behavior are not well defined at the moment, but any solution is probably fine at the moment until we actually implement those badge types.

**Comment by kieckhafer** [comment]
So we don't want to keep a simple `Badge` component as well? What you're suggesting seems to keep the same situation I was mentioning, where the `Badge` is permanently linked to be an inventory badge if all the inventory logic is inside of it.

Steps 2-5 make sense, my thought was to keep the existing `Badge` component and still use it inside the new `BadgeOverlay` component (what I was calling `InventoryBadge`), and just use it as a display Component that has all props and logic passed into it.

**Comment by aldeed** [comment]
Keeping it as a display component would be fine, too. Whatever is cleanest and easiest.

I think `BadgeOverlay` (not `Badge`) can have the logic for which badges become primary and secondary, given a list of boolean characteristics about a product. That is essentially what is in Badge right now, but updated to follow the rules in this issue description. There isn't really anything inventory-specific about this logic, other than the name `INVENTORY_STATUS`, which you can maybe change to `BADGE_TYPES` to make everything clearer.

The `inventoryStatus` util function is currently where the rest of the logic lives. It might be best to move this function call into `BadgeOverlay`, and feed it individual booleans instead of a full product. So `BadgeOverlay` usage would look something like this:

```js
<BadgeOverlay isSoldOut={product.isSoldOut}  isBackorder={product.isBackorder} {/* etc. */}>
  {/* some product image rendering */}
</BadgeOverlay>
```

And in `BadgeOverlay` render, you'd call `inventoryStatus({ isSoldOut, isBackorder, // etc. })` with those values coming from the props. `inventoryStatus` would maybe be changed to return `{ primaryBadge, secondaryBadge }` or whatever makes sense.
